### ISSUE TITLE
README.md mentions `webtreemap` which doesn't seem to exist

### ISSUE THREAD

**Issue by eseidelGoogle** [evmar/webtreemap#17]
I suspect `webtreemap` is an alias in your shell to `node cli.ts`?

**Comment by evmar** [comment]
You have to run 'npm install', then it shows up in `node_modules/.bin/webtreemap`.  I'm never quite sure whether to document this (for people unfamiliar with the node world) because I never see it documented in other comparable apps.

**Comment by eseidelGoogle** [comment]
`npm install` doesn't seem to be enough.  Are you sure that's all I need to run? :)

**Comment by evmar** [comment]
I am sorry for not fixing this sooner.  I have updated the README with install instructions:

https://github.com/evmar/webtreemap#command-line

The normal way to install a node package is via 'npm install' as written there.  If you have the code from git then you have to dig the program out from the build directory, which I've now also documented.

**Comment by tuket** [comment]
Hi, I'm also having trouble installing webtreemap.
I've tried two things:

- Running sudo npm i webtreemap from my `~/` directory.
The output was:

```
tuket@asus:~$ sudo npm i webtreemap
[sudo] password for tuket: 
/home/tuket
└── webtreemap@2.0.1 

npm WARN enoent ENOENT: no such file or directory, open '/home/tuket/package.json'
npm WARN tuket No description
npm WARN tuket No repository field.
npm WARN tuket No README data
npm WARN tuket No license field.
```
