### ISSUE TITLE
cli.js seem to assume a ../dist path exists

### ISSUE THREAD

**Issue by eseidelGoogle** [evmar/webtreemap#18]
```
%du -a /Users/eseidel/Downloads/flutter  | node cli.js -o out.html    [/src/webtreemap]

{ Error: ENOENT: no such file or directory, open '/src/webtreemap/../dist/webtreemap.js'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/src/webtreemap/../dist/webtreemap.js' }
```

**Comment by eseidelGoogle** [comment]
I've compiled with `tsc -w -p .` . Not sure if that's the correct command or not.

**Comment by tsarevfs** [comment]
It works after I renamed "build" directory (generated by tsc manual run in webtreemap root) to "dist".
But it generates non-working html.

I try to use webtreemap to visualize data generated by buildbloat. Only thing that helps me is using v1 branch with patch:
```
--- a/webtreemap.js
+++ b/webtreemap.js
@@ -78,7 +78,7 @@ function makeDom(tree, level) {
   }
 
   for(key in tree.data){
-    if(key != '$area'){
+    if(key != '$area' && key != '$dominant_symbol'){
       dom.setAttribute('data-' + key, tree.data[key]);
     }
   }
```

It will be really useful to document CLI usage for non js programmers.

**Comment by evmar** [comment]
I am sorry for not fixing this sooner. I have updated the README with install instructions:

https://github.com/evmar/webtreemap#command-line

The normal way to install a node package is via 'npm install' as written there, which pulls the built program from npm and gives you a runnable binary. If you get the code from git then you have to dig the program out from the build directory, which I've now also documented.
